# Site
name: "Alon Shrestha"
title: "alon'sTech Blog"
description: "Blog related to tech tutorial, product, event, news written in plain and ease to understand"
meta_description: "Blog related to tech tutorial, product, event, news written in plain and ease to understand"
logo: 'assets/images/personal/head.jpg'
favicon: assets/images/favicon.png
paginate: 6
url: 'https://blog.alonshrestha.com.np'
baseurl: ''
include: ["_pages"]
# Social Media

email: 'blog.alonshrestha.com.np@gmail.com'
linkedin: https://linkedin.com/in/alonshrestha
instagram: https://instagram.com/a.l_o.n
github: https://github.com/alonshrestha
twitter: https://twitter.com/AlonShrestha

google_analytics: 'UA-145866170-1'
disqus: 'alonsTechBlog'
sharethis: "<script type='text/javascript' src='https://platform-api.sharethis.com/js/sharethis.js#property=5d6693485fea9f001288d6b1&product=sticky-share-buttons' async='async'></script>"
#sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

permalink: /:title/


# Authors
authors:
  alonshrestha:
    name: Alon Shrestha
    display_name: Alon Shrestha
    gravatar: 328cf0c5d7b7464fbc7a35d54a90c778
    twitter: https://twitter.com/AlonShrestha
    web: https://alonshrestha.com.np
    description: " A Computer Science Student "




# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
